### ISSUE TITLE
Large images cause Negative Pointer#malloc size (ArgumentError) due to overflow

### ISSUE THREAD

**Issue by spencerwi** [l3kn/stumpy_core#10]
I recommend allowing UInt64 for the width/height of stumpy's images, as currently a large enough image causes `Slice.new(width * height, ...)` to overflow, since the `width` and `height` arguments only accept `Int32`. Accepting `UInt64` will allow for larger images.

```
Unhandled exception: Negative Pointer#malloc size (ArgumentError)
  from /usr/local/Cellar/crystal/0.27.0/src/pointer.cr:0:7 in 'malloc'
  from /usr/local/Cellar/crystal/0.27.0/src/slice.cr:476:5 in 'new'
  from /private/tmp/AdventOfCode2018/day10/lib/stumpy_core/src/stumpy_core/canvas.cr:33:17 in 'initialize'
  from /private/tmp/AdventOfCode2018/day10/lib/stumpy_core/src/stumpy_core/canvas.cr:32:5 in 'initialize'
  from /private/tmp/AdventOfCode2018/day10/lib/stumpy_core/src/stumpy_core/canvas.cr:32:5 in 'new'

```

**Comment by l3kn** [comment]
Thanks for the suggestion, I'll look into it.

I'm not sure why I chose `Int32` instead of `UInt32`,
but 32 bit still seem reasonable because that's how width/height are stored in the png format.
Of course the overflow still needs to be fixed.

Could you send me some code or a test image that causes the error?

__Edit:__

I found another problem, [`Slice` internally uses `Int32`s to store its size](https://github.com/crystal-lang/crystal/blob/ccf46c095a7e10cb120d4d04c96333858be4aaa2/src/slice.cr#L46).

Allowing for larger image sizes would require more extensive changes to this library
and the main image writers, possibly at the cost of performance.

How big is the image you are trying to create
and what are you intending to do with it?

**Comment by spencerwi** [comment]
I'm working through Advent of Code challenges, and [today's challenge](https://adventofcode.com/2018/day/10) involves working with _really_ big grids -- too large to really display in text form well, so I thought I'd deal with images.

My code is as follows:

```crystal
require "stumpy_png" # text output is too big for the terminal, so we spit out images
include StumpyPNG

alias X = Int32
alias Y = Int32
class Star
  getter position, velocity

  def initialize(@position : Tuple(X, Y), @velocity : Tuple(X, Y))
  end

  def tick
    x, y = @position
    vx, vy = @velocity
    @position = {x + vx, y + vy}
  end

  def self.parse(input_line : String) : Star
    if /position=<\s*(?<x>-?\d+),\s*(?<y>-?\d+)> velocity=<\s*(?<vx>-?\d+),\s*(?<vy>-?\d+)/ =~ input_line
      x, y, vx, vy = ["x", "y", "vx", "vy"].map {|group| $~[group].to_i}
      return Star.new(position = {x, y}, velocity = {vx, vy})
    else
      raise "Invalid line: #{input_line}"
    end
  end
end

class Day10
  @stars : Array(Star)

  def initialize(input_lines : Array(String))
    @stars = input_lines.map {|line| Star.parse(line)}
  end

  def part_a
    loop do
      # We don't need all the empty space around the edges, so we
      # "bound" our image canvas by the farthest-out stars
      smallest_x, largest_x = @stars.minmax_of(&.position[0])
      smallest_y, largest_y = @stars.minmax_of(&.position[1])

      # Normalize to a 0-based canvas in case we have negative positions
      canvas_w =
        if smallest_x < 0
          # shift largest and smallest over so that smallest is 0
          largest_x += smallest_x.abs
          smallest_x = 0
          largest_x + 1
        else
          (largest_x - smallest_x) + 1
        end

      canvas_h =
        if smallest_y < 0
          # shift largest and smallest over so that smallest is 0
          largest_y += smallest_y.abs
          smallest_y = 0
          largest_y + 1
        else
          (largest_y - smallest_y) + 1
        end

      puts smallest_x, largest_x
      puts smallest_y, largest_y

      canvas = Canvas.new(canvas_w, canvas_h)

      (smallest_x..largest_y).each do |y|
          (smallest_y..largest_x).each do |x|
            # smallest_x goes on the canvas at x = 0, same for smallest_y and
            # y = 0, so we remove the "offset" to ensure that happens.
            canvas_x, canvas_y = {x - smallest_x, y - smallest_y}
            puts canvas_x, canvas_y

            color =
              if @stars.any? {|star| star.position == {x,y}}
                RGBA::WHITE # Stars are white dots
              else
                RGBA::BLACK # Night sky is black
              end

            canvas[canvas_x, canvas_y] = color
        end
      end

      StumpyPNG.write(canvas, "nightsky.png")

      # Write the image to a file, and wait for user to hit enter
      puts "Wrote image file to nightsky.png; hit enter to move forward 1 second"
      _ = read_line
      @stars.each(&.tick)
    end
  end

  def part_b
  end

  def print_usage_and_exit
    puts "Usage: day10 [A|a|B|b]"
    exit 1
  end
end

day10 = Day10.new(File.read_lines("input.txt"))
if ARGV.size > 0
  if ARGV.includes?("a") || ARGV.includes?("A")
    day10.part_a
  elsif ARGV.includes?("b") || ARGV.includes?("B")
    day10.part_b
  else
    day10.print_usage_and_exit
  end
else
  day10.print_usage_and_exit
end
```

Inputs can be obtained here: https://adventofcode.com/2018/day/10/input

They wind up pretty quickly in the X00,000 by X00,000 range, which makes for a pretty big image. 

All that to say: if there's significant re-engineering needed, then my use-case doesn't fit this lib (not the other way around), and I should find a different approach. Thanks for the really quick response, and for taking a look into how costly the changes would be!

**Comment by l3kn** [comment]
What a nice problem,
from the description it sounds like after some amount of steps
all points will be close enough together to fit into a normal sized image
(or even a terminal window).

<details>
  <summary>Possible spoiler</summary>
  I'd store a list of points and calculate their bounding box after each step,
  then display it in the terminal or as an image
  once this bounding box is below some size
</details>

**Comment by l3kn** [comment]
I've changed `Canvas.new` to throw an error if the size is to big,
otherwise there could have been some combinations of `width` and `height`
that lead to a broken / unusable `Canvas`
without any errors (like the allocation error you got)

**Comment by spencerwi** [comment]
Yeah, that's the approach I wound up taking, which eventually got me to small enough bounding boxes the point where text output was sufficient. It's a clever puzzle -- I highly recommend the rest of the Advent of Code challenges.

Anyhow, thanks for checking into this -- I might have to circle back around on the whole slice-sizing thing in Crystal some time.
