### ISSUE TITLE
Errors after upgrading to Crystal 0.35.0

### ISSUE THREAD

**Issue by ptcodes** [l3kn/stumpy_core#13]
The library seems to be incompatible with the latest version of Crystal.

How to replicate:
```
canvas = StumpyPNG.read("image.png")
StumpyPNG.write(canvas, "output.png")
```

Output:
```
crystal run test.cr                                                                                                                                             ⏎
Warning: Zlib is deprecated, use Compress::Zlib
Showing last frame. Use --error-trace for full trace.

In /usr/local/Cellar/crystal/0.35.0/src/io/encoding.cr:42:23

 42 | bytes_written &+= io.write(outbuf.to_slice[0, outbuf.size - outbytesleft])
                    ^-
Error: no overload matches 'Int64#&+' with type (Int64 | Nil)

Overloads are:
 - Int64#&+(other : Int8)
 - Int64#&+(other : Int16)
 - Int64#&+(other : Int32)
 - Int64#&+(other : Int64)
 - Int64#&+(other : Int128)
 - Int64#&+(other : UInt8)
 - Int64#&+(other : UInt16)
 - Int64#&+(other : UInt32)
 - Int64#&+(other : UInt64)
 - Int64#&+(other : UInt128)
Couldn't find overloads for these types:
 - Int64#&+(other : Nil)
```

Potentially related to the Zlib library:
>Warning: Zlib is deprecated, use Compress::Zlib

As per:
https://crystal-lang.org/2020/06/09/crystal-0.35.0-released.html

> Some other clean-ups: Flate, Gzip, Zip, and Zlib were moved inside Compress module in #8886. Flate was renamed to Compress::Deflate, actually. You might need to require "compress/gzip" and change some constants here or there. The require "gzip" is still available but will show a deprecation warning.

**Comment by l3kn** [comment]
This is a known issue (https://github.com/stumpycr/stumpy_png/issues/28) with stumpy_png, stumpy_core itself should not be affected by it.

The relevant changes in crystal have been reverted since the release of 0.35.0
and stumpy_png will be updated once 0.35.1 comes out.
