### ISSUE TITLE
Use lib in project 

### ISSUE THREAD

**Issue by ghost** [l3kn/stumpy_core#6]
I set up a project using crystal init and added and doeneloaded this requirement using the package manager

However I can not find documentation on how to compile the whole Programm (I know how to compile a single file) and how to require the library properly 

Include „StumpyCore“ gives a parsing exception like „expecting token ...“

Thanks in advance

**Comment by l3kn** [comment]
Hi, can you please upload your code (e.g. at https://gist.github.com/)
and post the whole error message?

**Comment by ghost** [comment]
Sorry but I have no Code setup yet cause crystal fails at the first line at the import.

My first file is in the src directory (created by crystal init lib) which I assume is correct.

If there is any available I would gladly read documentation on how to handle dependencies apart from just pulling/ updating them. 

Thanks very much for the quick response!

**Comment by ghost** [comment]
The whole error message is:
„Syntax error in main.cr:1: expecting token „CNST“, not „DELIMETER_START“

Include „StumpyCore“

**Comment by l3kn** [comment]
The correct syntax would be (no „“s)

``` crystal
require "stumpy_core"
include StumpyCore

# Do some stuff
```

What are you trying to build?
This is just a collection of interface classes for
working with images,
if you actually want to read or write image files,
a good place to start would be [stumpy_png](https://github.com/stumpycr/stumpy_png).

The readme there includes a short example how to read and write image files.

**Comment by ghost** [comment]
I somehow totally missed the require, now I get 
Error in main.cr:1: while requiring "stumpy_core": can't find file 'stumpy_core' relative to '~/Desktop/colorlib/src/colorlib'

require "stumpy_core"
^

note:
stumpy is located in "~/Desktop/colorlib/src/lib" after "crystal deps"

I first need to just want to get some colors printed out to a file/ some files for a simple program.

May I ask one further question?
What is supposed to go into the file like "stumpy_core/src/stumpy_core.cr" in your example?
Is this the file you use to build the whole thing like "crystal stumpy_core/src/stumpy_core.cr" (or run/ build command as required)

the default file has 
```
require "./colorlib/*"

module Colorlib
  # TODO Put your code here
end
```
which does not even seem to be legit crystal syntax because I get 
```
Error in colorlib.cr:1: while requiring "./colorlib/*"

require "./colorlib/*"
```
when I run it

sorry if this is out of place for this library but I could not yet figure this out based on the crystal docs.

thanks

**Comment by l3kn** [comment]
Did you run `shards install`?
And from where are you running `crystal run`?
It should work if you `cd` to the folder first.

`stumpy_core/src/stumpy_core.cr`is what is being required when you do `require "stumpy_core"`, either most of the code is in there or it has some requires on its own.

**Comment by ghost** [comment]
I did "shards install" although I believe "crystal deps" did already pull in the library 

I am at "~/Desktop/colorlib/src/colorlib" now and get 
```
Error in main.cr:1: while requiring "stumpy_core": can't find file 'stumpy_core' relative to '/Users/benediktmandelkow/Desktop/colorlib/src/colorlib'

require "stumpy_core"
```
after "crystal run main.cr"




is there any reason why a default "crystal init lib xyz" does produce an error when running xyz/src/xyz.rb ?
```
rror in xyz.cr:1: while requiring "./xyz/*"

require "./xyz/*"
^
```
(your "stumpy_core/src/stumpy_core.cr" in your lib passes just fine, the default seems weird to me though)

thanks

**Comment by l3kn** [comment]
Sounds like an issue related to crystal, not to this library in particular.
What is inside your `shard.yml`?

**Comment by ghost** [comment]
so let me try to give more information by running a fresh project 
``` Bash
crystal init lib test && touch test/src/test/test_main.cr
```
then I modify the shard.yml as follow

``` YAML
name: test
version: 0.1.0

authors:
  - <>

crystal: 0.23.1

dependencies:
  stumpy_core:
    github: stumpycr/stumpy_core
```
and run `shard install`

I modify test_main.cr as follow 
``` Crystal
#test_main.cr

require "stumpy_core"
include StumpyCore

# Do some stuff

```

and then run `crystal run src/test.cr`

and now it actually compiles... I am a bit puzzled but thanks very much for the help


One further question please:
Is there any information about call by reference vs value in crystal? I could not find any and would post an issue on their repo otherwise.

**Comment by l3kn** [comment]
Nice, I'm not sure what went wrong before.

Did you take a look at the [Crystal Docs](https://crystal-lang.org/docs/)?
I'd say until you run into performance problems the difference between structs and classes /
call by reference vs value does not matter that much.

**Comment by ghost** [comment]
yeah I did a fair bit but actually read that bit some time ago and missed it so good head up,
I just like to know for debugging. 

maybe I find out about what issue I had and report back

**Comment by ghost** [comment]
[I did "shards install" although I believe "crystal deps" did already pull in the library](https://github.com/stumpycr/stumpy_core/issues/6#issuecomment-331536489)

[turns out this is actually the case](https://github.com/crystal-lang/crystal/issues/4613#issuecomment-328835426)

hope this interested you ;)
really nice people so far all around crystal I have to say!
